spring:
  datasource:
    username: root
    password: 1q2w3e4r!
    url: jdbc:mysql://localhost:3306/docker_demo?useUnicode=true&characterEncoding=utf8
  jpa:
    hibernate:
      ddl-auto: create-drop
